### ISSUE TITLE
can't find clang on debian

### ISSUE THREAD

**Issue by steveklabnik** [manuels/cxx2rs#7]
I'm getting

```
clang.cindex.LibclangError: libclang.so: cannot open shared object file: No such file or directory. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
```

libclang is on my system:

```
/usr/lib/llvm-3.5/lib/libclang.so
```

any ideas?

**Comment by manuels** [comment]
The "easy" fix would be calling cxx2rs like this:

    LD_LIBRARY_PATH=/usr/lib/llvm-3.5/lib cxx2rs ...

But to be honest, I have no clue why [`clang.cindex.Config.set_library_file(find_library('clang'))`](https://github.com/manuels/cxx2rs/blob/master/cxx2rs/__main__.py#L11) does not work.

**Comment by steveklabnik** [comment]
```
$ LD_LIBRARY_PATH=/usr/lib/llvm-3.5/lib cxx2rs v8 ~/src/v8/include/v8.h  > src/lib.rs
Traceback (most recent call last):
  File "/usr/local/bin/cxx2rs", line 9, in <module>
    load_entry_point('cxx2rs==0.3.5', 'console_scripts', 'cxx2rs')()
  File "/usr/local/lib/python2.7/dist-packages/cxx2rs/__main__.py", line 69, in main
    del all_enums['']
KeyError: ''
```

Farther!

(I'm trying to wrap v8)

**Comment by manuels** [comment]
I just pushed a commit that should fix this bug.

**Comment by manuels** [comment]
I just saw that you want to port v8, which is C++.
In spite of the name **cxx**2rs, it currently does not support C++. I didn't have the use case, yet. But with a little bit of work, I think it would be quite possible to make cxx2rs work for C++ code.

**Comment by steveklabnik** [comment]
ahhh i just totally mis-read the Readme, then. Thanks!

**Comment by manuels** [comment]
Looks more like I totally mis-wrote the Readme ;)
I will fix that later today.
